---
- name: install PostgreSQL
  apt:
    name:
      - postgresql
      - postgresql-client
      - python3-psycopg2
    state: present
    cache_valid_time: 3600
  become: yes

- name: create a user in PostgreSQL
  postgresql_user:
    name: "{{ postgresql__user_name }}"
    password: "{{ postgresql__user_password }}"
    role_attr_flags: NOSUPERUSER,NOCREATEROLE,NOCREATEDB,INHERIT,LOGIN,NOREPLICATION,NOBYPASSRLS
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true

- name: create a database in PostgreSQL
  postgresql_db:
    name: "{{ postgresql__db_name }}"
    owner: "{{ postgresql__user_name }}"
    encoding: UTF8
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
