---
- hosts: all

  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - role: ufw
    - role: utils
    - role: sudo
      tags: users
    - role: users
      tags: users
    - role: postgresql
    - role: phoenix_app
    - role: nginx
