---
- name: create root directory
  file:
    path: "{{ phoenix_app__root_path }}"
    state: directory
    owner: root
    group: "{{ phoenix_app__deploy_group }}"
    mode: "2775"
  become: true

- name: create releases directory
  file:
    path: "{{ phoenix_app__root_path }}/releases"
    state: directory
    owner: root
    group: "{{ phoenix_app__deploy_group }}"
    mode: "2775"
  become: true

- name: create shared directory
  file:
    path: "{{ phoenix_app__root_path }}/shared"
    state: directory
    owner: root
    group: "{{ phoenix_app__deploy_group }}"
    mode: "2755"
  become: true

- name: create tmp directory
  file:
    path: "{{ phoenix_app__root_path }}/shared/tmp"
    state: directory
    owner: "{{ phoenix_app__service_user }}"
    group: "{{ phoenix_app__deploy_group }}"
    mode: "2770"
  become: true

- name: create uploads directory
  file:
    path: "{{ phoenix_app__root_path }}/shared/uploads"
    state: directory
    owner: "{{ phoenix_app__service_user }}"
    group: "{{ phoenix_app__deploy_group }}"
    mode: "2770"
  become: true

- name: create config directory
  file:
    path: "{{ phoenix_app__root_path }}/config"
    state: directory
    owner: root
    group: "{{ phoenix_app__deploy_group }}"
    mode: "2755"
  become: true

- name: create config file with env
  template:
    src: env.j2
    dest: "{{ phoenix_app__root_path }}/config/env"
    owner: root
    group: "{{ phoenix_app__deploy_group }}"
    mode: "0640"
  become: yes
