---
- name: create phoenix app service's unit file in systemd
  template:
    src: app_name.service.j2
    dest: /etc/systemd/system/{{ phoenix_app__app_name }}.service
    owner: root
    group: root
    mode: "0644"
  become: yes
  register: systemd_unit_file
  notify:
    - restart phoenix app

- name: reload systemd
  systemd:
    daemon_reload: yes
  become: yes
  when: systemd_unit_file.changed

- name: enable phoenix app service in systemd
  systemd:
    name: "{{ phoenix_app__app_name }}"
    enabled: yes
  become: yes

- name: allow deploy group to restart the phoenix app service
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%deploy\sALL='
    line: "%{{ phoenix_app__deploy_group }}	ALL=(ALL) NOPASSWD: /bin/systemctl restart {{ phoenix_app__app_name }}"
    validate: /usr/sbin/visudo -cf %s
  become: yes
