---
- name: create users
  user:
    state: present
    system: "{{ item.system | default(omit) }}"
    name: "{{ item.name }}"
    groups: "{{ item.groups | default([]) }}"
    shell: /bin/bash
    create_home: "{{ item.create_home | default(omit) }}"
  become: true
  with_items: "{{ users }}"

- name: set authorized keys
  authorized_key:
    state: present
    user: "{{ item.name }}"
    key: "{{ item.authorized_key | default(None) }}"
    exclusive: True
  become: true
  with_items: "{{ users }}"
