---
- name: create users
  user:
    state: present
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    shell: /bin/bash
  become: true
  with_items: "{{ users }}"

- name: set authorized keys
  authorized_key:
    state: present
    user: "{{ item.name }}"
    key: "{{ item.authorized_key }}"
    exclusive: True
  become: true
  with_items: "{{ users }}"
